DROP FUNCTION GET_USER_BY_TOKEN;
DROP FUNCTION VALIDATE_USER_CREDENTIALS;
DROP FUNCTION VALIDATE_USER_TOKEN;
DROP PROCEDURE ADD_USER_CREDENTIALS;
DROP PROCEDURE ADD_USER_TOKEN;
DROP PROCEDURE DELETE_USER_CREDENTIALS;

DROP TABLE USER_TOKENS;
DROP TABLE USER_CREDENTIALS;

COMMIT;