SELECT GET_RPI_ACTIONS_AFTER(RPI_ID, to_timestamp('07-02-2018 12:00:00.00', 'DD-MM-YYYY HH24:MI:SS.FF'), 10) FROM RPI_DEVICES;

SELECT GET_LATEST_DATE_ON_ACTIONS(RPI_ID) FROM RPI_DEVICES;

SELECT GET_RPI_BY_USER(USER_LOGIN) FROM USER_CREDENTIALS;